#include <algorithm> 
#include <iostream>
#include <sstream>
#include <fstream>
#include <iomanip>
#include <string>
#include <random>
#include <chrono>
#include <list>

using std::chrono::high_resolution_clock;
using std::uniform_int_distribution;
using std::stringstream;
using std::setprecision;
using std::accumulate;
using std::to_string;
using std::ifstream;
using std::ofstream;
using std::getline;
using std::mt19937;
using std::string;
using std::fixed;
using std::left;
using std::setw;
using std::sort;
using std::list;
using std::cout;
using std::cin;
